use master 
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'SOCCER')
BEGIN
    CREATE DATABASE SOCCER;
END
go 
use SOCCER;
go
GO
create table USERS(
	PHONENUM VARCHAR(11) NOT NULL,
	USERNAME NVARCHAR(30) NOT NULL,
	ROLE VARCHAR(10) NOT NULL,
	CreateAt Date NOT NULL,
	UpdatedAt Date NOT NULL,
	Password CHAR(50) NOT NULL,
	CONSTRAINT PK_PHONENUM PRIMARY KEY(PHONENUM)
)
create table TEAM(
	TEAMID VARCHAR(6) NOT NULL,
	TEAMNAME NVARCHAR(10) NOT NULL,
    NUMBEROFMEMBER SMALLINT NOT NULL,
	CONSTRAINT PK_TEAMID PRIMARY KEY(TEAMID)
)
CREATE TABLE PLAYER(
	PLAYERID VARCHAR(6) NOT NULL,
	PLAYERNAME NVARCHAR(30) NOT NULL,
	PLAYERNUMBER SMALLINT NOT NULL,
	DOB DATETIME NOT NULL,
	TEAMID VARCHAR(6) NOT NULL,
	CAPTAIN VARCHAR(10) NOT NULL,
	CONSTRAINT PK_PLAYERID PRIMARY KEY(PLAYERID),
	constraint fk_TEAMID foreign key(TEAMID) references TEAM(TEAMID)
)

CREATE TABLE TOUR
(
	TOURID VARCHAR(6) NOT NULL,
	TOURNAME NVARCHAR(30) NOT NULL,
	DATESTART DATE NOT NULL,
	DATEEND DATE NOT NULL,
	CURRENTSTATUS SMALLINT NOT NULL,
	CONSTRAINT PK_TOURID PRIMARY KEY(TOURID)
)

CREATE TABLE ROUND
(
	ROUNDID VARCHAR(6),
	ROUNDNAME VARCHAR(10) NOT NULL,
	TOURID VARCHAR(6),
	CONSTRAINT PK_ROUNDID PRIMARY KEY(ROUNDID),
	CONSTRAINT FK_TOURIDR FOREIGN KEY(TOURID) REFERENCES TOUR(TOURID)
	
)
create table MATCH
(
	MATCHID VARCHAR(6) NOT NULL,
	TEAM1_SCORE SMALLINT ,
	TEAM2_SCORE SMALLINT ,
	TEAMID1 VARCHAR(6) NOT NULL,
	TEAMID2 VARCHAR(6) NOT NULL,
	MATCHDAY DATETIME NOT NULL,
	GOAL1 SMALLINT ,
	GOAL2 SMALLINT ,
	CARDRED1 SMALLINT,
	CARDRED2 SMALLINT,
	CARDYELLOW1 SMALLINT,
	CARDYELLOW2 SMALLINT,
	ROUNDID VARCHAR(6) NOT NULL,
	CONSTRAINT PK_MATCHID PRIMARY KEY(MATCHID),
	constraint fk_TEAMID1 foreign key(TEAMID1) references TEAM(TEAMID),
	constraint fk_TEAMID2 foreign key(TEAMID2) references TEAM(TEAMID),
	CONSTRAINT FK_ROUNDID FOREIGN KEY(ROUNDID) REFERENCES ROUND(ROUNDID)
)


CREATE TABLE SUMMARY_OF_TEAM_IN_TOUR
(
	TOURID VARCHAR(6) NOT NULL,
	TEAMID VARCHAR(6) NOT NULL,
	LOSS SMALLINT NOT NULL,
	WIN SMALLINT NOT NULL,
	APPELLATION VARCHAR(30),
	DIFFERENCE SMALLINT NOT NULL,
	CONSTRAINT FK_TOURIDST FOREIGN KEY(TOURID) REFERENCES TOUR(TOURID),
	CONSTRAINT FK_TEAMIDSUM FOREIGN KEY(TEAMID) REFERENCES TEAM(TEAMID)
)
CREATE TABLE RESGIST_TOUR
(
	TEAMID VARCHAR(6) NOT NULL,
	TOURID VARCHAR(6) NOT NULL,
	DATEAT SMALLDATETIME NOT NULL,
	CONSTRAINT FK_REPID FOREIGN KEY(TEAMID) REFERENCES TEAM(TEAMID),
	CONSTRAINT FK_TOURID FOREIGN KEY(TOURID) REFERENCES TOUR(TOURID)
)

CREATE TABLE PLAYER_IN_MATCH
(
	MATCHID VARCHAR(6) NOT NULL,
	PLAYERID VARCHAR(6) NOT NULL,
	ROLEINMATCH VARCHAR(10) NOT NULL,
	CONSTRAINT FK_MATCHID FOREIGN KEY(MATCHID) REFERENCES MATCH(MATCHID),
	CONSTRAINT FK_PLAYERID FOREIGN KEY(PLAYERID) REFERENCES PLAYER(PLAYERID)
)
CREATE TABLE TEAM_IN_ROUND
(
	MATCHLOSS SMALLINT NOT NULL,
	MATCHWIN SMALLINT NOT NULL,
	CARDYELLOW SMALLINT NOT NULL,
	CARDRED SMALLINT NOT NULL,
	RANKROUND SMALLINT NOT NULL,
	DIFFERENCE SMALLINT NOT NULL,
	
)

go
CREATE OR ALTER FUNCTION AUTO_TEAMID()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(TEAMID) FROM TEAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(TEAMID, 5)) FROM TEAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'T0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1,2)
				WHEN @ID >= 9 and @ID < 99 THEN 'T000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
					WHEN @ID >= 99 and @ID < 999 THEN 'T00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
						WHEN @ID >= 999 and @ID < 9999 THEN 'T00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
							WHEN @ID >= 9999 and @ID < 99999 THEN 'T0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
								WHEN @ID >= 99999 THEN 'T' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

alter table TEAM 
ADD CONSTRAINT IDTEAM DEFAULT DBO.AUTO_TEAMID() FOR TEAMID
GO

CREATE OR ALTER FUNCTION AUTO_PLAYERID()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(PLAYERID) FROM PLAYER) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(PLAYERID, 5)) FROM PLAYER
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'P0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1,2)
				WHEN @ID >= 9 and @ID < 99 THEN 'P000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
					WHEN @ID >= 99 and @ID < 999 THEN 'P00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
						WHEN @ID >= 999 and @ID < 9999 THEN 'P00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
							WHEN @ID >= 9999 and @ID < 99999 THEN 'P0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
								WHEN @ID >= 99999 THEN 'P' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

alter table PLAYER 
ADD CONSTRAINT IDPLAYER DEFAULT DBO.AUTO_PLAYERID() FOR PLAYERID
GO

CREATE OR ALTER FUNCTION AUTO_MATCHID()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MATCHID) FROM MATCH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MATCHID, 5)) FROM MATCH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'M0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1,2)
				WHEN @ID >= 9 and @ID < 99 THEN 'M000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
					WHEN @ID >= 99 and @ID < 999 THEN 'M00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
						WHEN @ID >= 999 and @ID < 9999 THEN 'M00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
							WHEN @ID >= 9999 and @ID < 99999 THEN 'M0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
								WHEN @ID >= 99999 THEN 'M' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

alter table MATCH 
ADD CONSTRAINT IDMATCH DEFAULT DBO.AUTO_MATCHID() FOR MATCHID
GO

CREATE OR ALTER FUNCTION AUTO_TOURID()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(TOURID) FROM TOUR) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(TOURID, 5)) FROM TOUR
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'G0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99 THEN 'G000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999 THEN 'G00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 and @ID < 9999 THEN 'G00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9999 and @ID < 99999 THEN 'G0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99999 THEN 'G' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

alter table TOUR 
ADD CONSTRAINT IDTOUR DEFAULT DBO.AUTO_TOURID() FOR TOURID
GO


CREATE OR ALTER FUNCTION AUTO_ROUNDID()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(ROUNDID) FROM ROUND) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(ROUNDID, 5)) FROM ROUND
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'R0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99 THEN 'R000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999 THEN 'R00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 and @ID < 9999 THEN 'R00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9999 and @ID < 99999 THEN 'R0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99999 THEN 'R' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

alter table ROUND
ADD CONSTRAINT IDROUND DEFAULT DBO.AUTO_ROUNDID() FOR ROUNDID
GO
--Data settings


use SOCCER

select * from USERS
--Select username from users where phonenum = '1234567890' and password = 'Admin1234@';
--Proc tour ==================================================================================================================================
use SOCCER
select * from TOUR

INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2023', '2023-06-01', '2023-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2024', '2024-06-01', '2024-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2025', '2025-06-01', '2025-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2026', '2026-06-01', '2026-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2027', '2027-06-01', '2027-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2028', '2028-06-01', '2028-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2029', '2029-06-01', '2029-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2030', '2030-06-01', '2030-07-15', 1);
INSERT INTO TOUR(TOURNAME, DATESTART, DATEEND,CURRENTSTATUS) VALUES ('World Cup 2031', '2031-06-01', '2031-07-15', 1);

--proc insert
use SOCCER
GO
CREATE or ALTER PROCEDURE dbo.InsertTour
    @TourName NVARCHAR(30),
    @DateStart DATE,
    @DateEnd DATE,
	@CURRENTSTATUS SMALLINT
AS
BEGIN
    INSERT INTO TOUR (TOURNAME, DATESTART, DATEEND,CURRENTSTATUS)
    VALUES (@TourName, @DateStart, @DateEnd, @CURRENTSTATUS);
END
GO
/*EXEC dbo.InsertTour 
    @TourName = 'World Cup 2032', 
    @DateStart = '2032-06-01', 
    @DateEnd = '2032-07-15';*/
---proc update 
CREATE OR ALTER PROCEDURE dbo.UpdateTour
	@TourName NVARCHAR(30),
	@DateStart DATE,
	@DateEnd DATE,
	@TourID varchar(6),
	@CURRENTSTATUS SMALLINT
  AS
    BEGIN
     UPDATE Tour 
     SET TourName=@TourName, DateStart = @DateStart, DateEnd= @DateEnd , CURRENTSTATUS = @CURRENTSTATUS
     WHERE TourID = @TourID
	END
GO
/*EXEC dbo.UpdateTour 
@TourName = 'World Cup 1032', 
@DateStart = '2032-06-01', 
@DateEnd = '2032-07-15',
@TourID = 'G00002'*/


---proc search 
CREATE OR ALTER PROCEDURE dbo.SeachTour
	@TourName NVARCHAR(30),
	@TourID varchar(6)
  AS
    BEGIN
	select TourName As N'Tên giải', TOURID AS N'Mã giải', DATESTART AS N'Ngày bắt đầu', DATEEND AS N'Ngày kết thúc' from TOUR WHERE TourName like ('%' + @TourName +'%') or  TOURID like ('%' + @TourId +'%');
	END
GO
--EXEC dbo.SeachTour 
--@TourName = '',
--@TourID = ''

---proc delete row 
CREATE OR ALTER PROCEDURE dbo.DeleteTour
	@TourID varchar(6)	
  AS
    BEGIN
	DELETE FROM Tour WHERE TourId = @TourId;
	END
GO
/*EXEC dbo.DeleteTour 
@TourID = 'G00002'*/

---proc load row 
CREATE OR ALTER PROCEDURE dbo.LoadTour
  AS
    BEGIN
	select TourName As N'Tên giải', TOURID AS N'Mã giải', DATESTART AS N'Ngày bắt đầu', DATEEND AS N'Ngày kết thúc' from TOUR
	END
GO
EXEC dbo.LoadTour 
GO

--proc user ==================================================================================================================================
use SOCCER
go
insert into USERS VALUES('1234567890',N'admin','admin', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Admin1234@');
insert into USERS VALUES('1234567891',N'admin','admin', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Admin1234@');
insert into USERS VALUES('1234567892',N'admin','admin', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Admin1234@');
insert into USERS VALUES('1234567893',N'admin','admin', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Admin1234@');
insert into USERS VALUES('1234567894',N'admin','admin', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Admin1234@');
insert into USERS VALUES('1234567895',N'collab','collab', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Collab1234@');
insert into USERS VALUES('1234567896',N'collab','collab', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Collab1234@');
insert into USERS VALUES('1234567897',N'collab','collab', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Collab1234@');
insert into USERS VALUES('1234567898',N'collab','collab', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Collab1234@');
insert into USERS VALUES('1234567899',N'collab','collab', CAST(N'2012-06-18 10:34:09.000' AS DateTime), CAST(N'2012-06-18 10:34:09.000' AS DateTime), 'Collab1234@');
select * from USERS
go
--proc insert
CREATE or ALTER PROCEDURE dbo.InsertUser
    @PHONE VARCHAR(11),
	@USERNAME NVARCHAR(30),
	@ROLE VARCHAR(10),
	@CreateAt Date,
	@UpdatedAt Date,
	@Password CHAR(50)
	AS
	BEGIN
		INSERT INTO USERS (PHONENUM, USERNAME, ROLE, CreateAt, UpdatedAt, Password) VALUES ( @PHONE, @USERNAME, @ROLE, @CreateAt, @UpdatedAt, @Password);
	END
GO
---proc update 
CREATE OR ALTER PROCEDURE dbo.UpdateUser
	@PHONENUM VARCHAR(11),
	@USERNAME NVARCHAR(30),
	@ROLE VARCHAR(10),
	@CreateAt Date,
	@UpdatedAt Date,
	@Password CHAR(50)	
  AS
    BEGIN
     UPDATE USERS 
     SET PHONENUM=@PHONENUM, USERNAME=@USERNAME, ROLE=@ROLE, CreateAt=@CreateAt, UpdatedAt=@UpdatedAt, Password =@Password
     WHERE PHONENUM = @PHONENUM
	END
GO

---proc search 
CREATE OR ALTER PROCEDURE dbo.SeachUser
	@TourName NVARCHAR(30),
	@TourID varchar(6)
  AS
    BEGIN
	select TourName As N'Tên giải', TOURID AS N'Mã giải', DATESTART AS N'Ngày bắt đầu', DATEEND AS N'Ngày kết thúc' from TOUR WHERE TourName like ('%' + @TourName +'%') or  TOURID like ('%' + @TourId +'%');
	END
GO
---proc delete row 
CREATE OR ALTER PROCEDURE dbo.DeleteTour
	@TourID varchar(6)	
  AS
    BEGIN
	DELETE FROM Tour WHERE TourId = @TourId;
	END
GO

---proc load row 
CREATE OR ALTER PROCEDURE dbo.LoadTour
  AS
    BEGIN
	select TourName As N'Tên giải', TOURID AS N'Mã giải', DATESTART AS N'Ngày bắt đầu', DATEEND AS N'Ngày kết thúc' from TOUR
	END
GO

----------------------------------Team----------------------------

use SOCCER
GO
CREATE or ALTER PROCEDURE dbo.InsertTeam
	@TEAMNAME NVARCHAR(10) ,
    @NUMBEROFMEMBER SMALLINT
AS
BEGIN
    INSERT INTO TEAM (TEAMNAME, NUMBEROFMEMBER)
    VALUES (@TEAMNAME, @NUMBEROFMEMBER);
END
GO
/*EXEC dbo.InsertTour 
    @TourName = 'World Cup 2032', 
    @DateStart = '2032-06-01', 
    @DateEnd = '2032-07-15';*/
---proc update 
CREATE OR ALTER PROCEDURE dbo.UpdateTeam
	@TEAMNAME NVARCHAR(10) ,
    @NUMBEROFMEMBER SMALLINT,
	@TEAMID varchar(6)	
  AS
    BEGIN
     UPDATE TEAM
     SET TEAMNAME = @TEAMNAME, NUMBEROFMEMBER = @NUMBEROFMEMBER
     WHERE TEAMID = @TEAMID
	END
GO
/*EXEC dbo.UpdateTour 
@TourName = 'World Cup 1032', 
@DateStart = '2032-06-01', 
@DateEnd = '2032-07-15',
@TourID = 'G00002'*/

CREATE OR ALTER PROCEDURE dbo.DeleteTeam
	@TeamID varchar(6)	
  AS
    BEGIN
	DELETE FROM Team WHERE TEAMID = @TEAMID;
	END
GO
/*EXEC dbo.DeleteTour 
@TourID = 'G00002'*/

---proc load row 
CREATE OR ALTER PROCEDURE dbo.LoadTeam
  AS
    BEGIN
	select TEAMNAME As N'Tên đội', TEAMID AS N'Mã đội', NUMBEROFMEMBER AS N'Số lượng thành viên' from TEAM
	END
GO
EXEC dbo.LoadTeam
GO

---------------------------------Player----------------------

use SOCCER
GO
CREATE or ALTER PROCEDURE dbo.InsertPlayer
	@PLAYERNAME NVARCHAR(30),
	@PLAYERNUMBER SMALLINT,
	@DOB DATETIME,
	@TEAMID VARCHAR(6),
	@CAPTAIN BIT
AS
BEGIN
    INSERT INTO PLAYER (PLAYERNAME, PLAYERNUMBER, DOB, TEAMID, CAPTAIN)
    VALUES (@PLAYERNAME, @PLAYERNUMBER, @DOB, @TEAMID, @CAPTAIN);
END
GO
/*EXEC dbo.InsertTour 
    @TourName = 'World Cup 2032', 
    @DateStart = '2032-06-01', 
    @DateEnd = '2032-07-15';*/
---proc update 
CREATE OR ALTER PROCEDURE dbo.UpdatePlayer
	@PLAYERNAME NVARCHAR(30),
	@PLAYERNUMBER SMALLINT,
	@DOB DATETIME,
	@TEAMID VARCHAR(6),
	@PLAYERID VARCHAR(6),
	@CAPTAIN BIT
  AS
    BEGIN
     UPDATE PLAYER
     SET PLAYERNAME = @PLAYERNAME, PLAYERNUMBER = @PLAYERNUMBER, DOB = @DOB, TEAMID = @TEAMID, CAPTAIN = @CAPTAIN
     WHERE PLAYERID = @PLAYERID
	END
GO
/*EXEC dbo.UpdateTour 
@TourName = 'World Cup 1032', 
@DateStart = '2032-06-01', 
@DateEnd = '2032-07-15',
@TourID = 'G00002'*/

CREATE OR ALTER PROCEDURE dbo.DeletePlayer
	@PLAYERID varchar(6)	
  AS
    BEGIN
	DELETE FROM PLAYER WHERE PLAYERID = @PLAYERID;
	END
GO
/*EXEC dbo.DeleteTour 
@TourID = 'G00002'*/

---proc load row 
CREATE OR ALTER PROCEDURE dbo.LoadPlayer
  AS
    BEGIN
	select PLAYERNAME As N'Họ tên', TEAMID AS N'Mã đội', PLAYERID AS N'Mã thành viên', DOB as N'Ngày sinh',PLAYERNUMBER AS N'Số áo', CAPTAIN AS N'Đội trưởng' from PLAYER
	END
GO
EXEC dbo.LoadPlayer
GO


-------------------------ROUND------------------
use SOCCER
GO
CREATE or ALTER PROCEDURE dbo.InsertRound
	@ROUNDNAME VARCHAR(10),
	@TOURID VARCHAR(6)
AS
BEGIN
    INSERT INTO ROUND ( ROUNDNAME, TOURID)
    VALUES ( @ROUNDNAME, @TOURID);
END
GO


CREATE OR ALTER PROCEDURE dbo.UpdateRound
	@ROUNDID VARCHAR(6),
	@ROUNDNAME VARCHAR(10),
	@TOURID VARCHAR(6)
  AS
    BEGIN
     UPDATE ROUND
     SET ROUNDID = @ROUNDID, ROUNDNAME = @ROUNDNAME, TOURID = @TOURID 
     WHERE ROUNDID = @ROUNDID
	END
GO
/*EXEC dbo.UpdateTour 
@TourName = 'World Cup 1032', 
@DateStart = '2032-06-01', 
@DateEnd = '2032-07-15',
@TourID = 'G00002'*/

CREATE OR ALTER PROCEDURE dbo.DeleteROUND
	@ROUNDID varchar(6)
  AS
    BEGIN
	DELETE FROM ROUND WHERE ROUNDID = @ROUNDID;
	END
GO
/*EXEC dbo.DeleteTour 
@TourID = 'G00002'*/

---proc load row 
CREATE OR ALTER PROCEDURE dbo.LoadRound
  AS
    BEGIN
	select ROUNDID As N'Mã vòng', ROUNDNAME AS N'Tên vòng', TOURID AS N'Mã giải' from ROUND
	END
GO
EXEC dbo.LoadRound
GO

CREATE OR ALTER PROCEDURE dbo.GetRoundById
	@TOURID VARCHAR(6)
  AS
    BEGIN
	select * from ROUND
	WHERE  TOURID = @TOURID;
	END
GO


------------------------Match-----------------------------
use SOCCER
GO
CREATE or ALTER PROCEDURE dbo.InsertMatch
	@TEAM1_SCORE SMALLINT,
	@TEAM2_SCORE SMALLINT ,
	@TEAMID1 VARCHAR(6),
	@TEAMID2 VARCHAR(6),
	@MATCHDAY DATETIME,
	@GOAL1 SMALLINT,
	@GOAL2 SMALLINT,
	@CARDRED1 SMALLINT,
	@CARDRED2 SMALLINT,
	@CARDYELLOW1 SMALLINT,
	@CARDYELLOW2 SMALLINT,
	@ROUNDID VARCHAR(10)
AS
BEGIN
    INSERT INTO MATCH (TEAMID1, TEAMID2, MATCHDAY, TEAM1_SCORE, TEAM2_SCORE, GOAL1, GOAL2, CARDRED1, CARDRED2, CARDYELLOW1, CARDYELLOW2, ROUNDID )
    VALUES (@TEAMID1, @TEAMID2, @MATCHDAY, @TEAM1_SCORE, @TEAM2_SCORE, @GOAL1, @GOAL2, @CARDRED1, @CARDRED2, @CARDYELLOW1, @CARDYELLOW2, @ROUNDID);
END
GO
/*EXEC dbo.InsertTour 
    @TourName = 'World Cup 2032', 
    @DateStart = '2032-06-01', 
    @DateEnd = '2032-07-15';*/
---proc update 
CREATE OR ALTER PROCEDURE dbo.UpdateMatch
	@MATCHID VARCHAR(6) ,
	@TEAM1_SCORE SMALLINT,
	@TEAM2_SCORE SMALLINT ,
	@TEAMID1 VARCHAR(6),
	@TEAMID2 VARCHAR(6),
	@MATCHDAY DATETIME,
	@GOAL1 SMALLINT,
	@GOAL2 SMALLINT,
	@CARDRED1 SMALLINT,
	@CARDRED2 SMALLINT,
	@CARDYELLOW1 SMALLINT,
	@CARDYELLOW2 SMALLINT,
	@ROUNDID VARCHAR(10)	
  AS
    BEGIN
     UPDATE MATCH
     SET TEAMID1 = @TEAMID1, TEAMID2 = @TEAMID2, MATCHDAY = @MATCHDAY, TEAM1_SCORE = @TEAM1_SCORE, TEAM2_SCORE = @TEAM2_SCORE, GOAL1 = @GOAL1, GOAL2 = @GOAL2, CARDRED1 = @CARDRED1, CARDRED2 = @CARDRED2, CARDYELLOW1 = @CARDYELLOW1, CARDYELLOW2 = @CARDYELLOW2, ROUNDID = @ROUNDID
     WHERE MATCHID = @MATCHID
	END
GO
/*EXEC dbo.UpdateTour 
@TourName = 'World Cup 1032', 
@DateStart = '2032-06-01', 
@DateEnd = '2032-07-15',
@TourID = 'G00002'*/


---proc search 
CREATE OR ALTER PROCEDURE dbo.SeachMatch
	@MATCHID VARCHAR(6) 
  AS
    BEGIN
	select Team1_Score As N'Điểm đội 1', TEAM2_SCORE AS N'Điểm đội 2', MATCHDAY AS N'Ngày bắt đầu', TEAMID1 AS N'Mã đội 1', TEAMID2 AS N'Mã đội 2', CARDRED1 AS N'Thẻ đỏ đội 1', CARDRED2 AS N'Thẻ đỏ đội 2', CARDYELLOW1 AS N'Thẻ vàng đội 1', CARDYELLOW2 AS N'Thẻ vàng đội 2', ROUNDID AS N'Mã vòng' from MATCH
	WHERE  MATCHID like ('%' + @MATCHID +'%');
	END
GO
--EXEC dbo.SeachTour 
--@TourName = '',
--@TourID = ''

---proc delete row 
CREATE OR ALTER PROCEDURE dbo.DeleteMatch
	@MATCHID varchar(6)	
  AS
    BEGIN
	DELETE FROM MATCH WHERE MATCHID = @MATCHID;
	END
GO
/*EXEC dbo.DeleteTour 
@TourID = 'G00002'*/

---proc load row 
CREATE OR ALTER PROCEDURE dbo.LoadMatch
  AS
    BEGIN
	select Team1_Score As N'Điểm đội 1', TEAM2_SCORE AS N'Điểm đội 2', MATCHDAY AS N'Ngày bắt đầu', TEAMID1 AS N'Mã đội 1', TEAMID2 AS N'Mã đội 2', CARDRED1 AS N'Thẻ đỏ đội 1', CARDRED2 AS N'Thẻ đỏ đội 2', CARDYELLOW1 AS N'Thẻ vàng đội 1', CARDYELLOW2 AS N'Thẻ vàng đội 2', ROUNDID AS N'Mã vòng' from MATCH
	END
GO
EXEC dbo.LoadMatch
GO


-------------------------TeamResgistTour----------------------

use SOCCER
GO
CREATE or ALTER PROCEDURE dbo.InsertTeamResgistTour
	@TEAMID VARCHAR(6),
	@TOURID VARCHAR(6) ,
	@DATEAT SMALLDATETIME
AS
BEGIN
    INSERT INTO RESGIST_TOUR ( TEAMID, TOURID, DATEAT)
    VALUES ( @TEAMID, @TOURID, @DATEAT);
END
GO

Create or ALTER PROCEDURE DBO.GetTeamResgistTour
AS
BEGIN 
	select * from RESGIST_TOUR
END
go


